[package]
name = "rum"
version = "0.1.0"
authors = ["Noah Daniels <ndaniels@mac.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.0.*"

[profile.release]
debug = true
lto = true
